### ISSUE TITLE
Viewing is too expensive

### ISSUE THREAD

**Issue by 3141592654** [EastsidePreparatorySchool/SpaceCritters#1]
My alien, ThinkingMachine, has a Boolean peaceful. If the Boolean is true, it will not run the fight code - copy-pasted from the Dalek - including initializing the view. Here is a screenshot of the peaceful ThinkingMachine:
![noview](https://cloud.githubusercontent.com/assets/12554811/14936418/fe3a9cb6-0ea0-11e6-8f5c-770de45af1cb.PNG)
The ThinkingMachines started reproducing ~ turn 1000 and grew rapidly, limited by the fact that they were dumb as stumps and kept running into stars. Here is the same ThinkingMachine with peaceful set to false:
![view](https://cloud.githubusercontent.com/assets/12554811/14936425/2f00d554-0ea1-11e6-93d3-8aa06f24fcfe.PNG)
They haven't reproduced at all. From this, I conclude that the energy needed to view one's surroundings is too expensive, as doing so every turn drains so much energy that the alien cannot reproduce.

**Comment by gunnarmein** [comment]
Your evidence is unconvincing. Your alien lives like there is no tomorrow - it will have to learn to save. However, I agree that the game was more interesting when views were free. Coming soon to a build near you.
